# experiment.yml
jobs:
  - command:
      creates: Trimer-P{pressure:.2f}-T{create_temp:.2f}.gsd
      cmd: >
        mpirun -np 12
        sdrun
        --pressure {pressure}
        --init-temp {init_temp}
        --temperature {create_temp}
        --lattice-lengths {cell_dims}
        --output {output}
        --steps {create_steps}
        create
        {creates}

  - command:
      requires: Trimer-P{pressure:.2f}-T{temperature:.2f}.gsd
      creates: Trimer-P{pressure:.2f}-T{create_temp:.2f}.gsd
      cmd: >
        mpirun -np 12
        sdrun
        --pressure {pressure}
        --init-temp {create_temp}
        --temperature {temperature}
        --output {output}
        --steps {equil_steps}
        equil
        {requires}
        {creates}

  - command:
      requires: Trimer-P{pressure:.2f}-T{temperature:.2f}.gsd
      cmd: >
        mpirun -np 12
        sdrun
        --pressure {pressure}
        --temperature {temperature}
        --output {output}
        --steps {steps}
        prod
        {requires}

variables:
  create_temp: 0.80
  create_steps: 10_000_000
  equil_steps: 100_000_000
  output: output
  steps: 200_000_000
  pressure: 1.00
  temperature:
    - 0.30
    - 0.32
    - 0.34
    - 0.36
    - 0.38
    - 0.40
    - 0.42
    - 0.44
    - 0.46
    - 0.50

pbs:
  setup:
    - export PATH="$HOME/.pyenv/versions/crystal/bin:$PATH"
  cpus: 12
  memory: 16gb
  walltime: 100:00:00
  project: PRJ-CrysGrowth
  o: logs
  j: oe

