{% set version = "0.3.0" %}

package:
  name: experi
  version: {{ version }}

about:
  home: https://github.com/malramsay64/experi
  license: MIT
  license_file: LICENSE

source:
  git_url: https://github.com/malramsay64/experi.git
  git_rev: v{{ version }}

requirements:
  build:
    - python {{ python }}
    - setuptools


  run:
    - {{ pin_compatible('python', max_pin='x.x') }}
    - pyyaml==5.*
    - click

build:
  number: 0
  noarch: python
  script: python setup.py install --single-version-externally-managed --record=record.txt
  entry_points:
    - experi = experi.run:main
